sudo: required
language: python
python:
  - "3.4"
addons:
  postgresql: "9.3"
  hosts:
    - db
services:
  - docker
install:
  - pip install tox
  - nvm install 0.12
env:
  matrix:
    - TOX_ENV=flake8
    - TOX_ENV=tests
    - TOX_ENV=frontend
    - TOX_ENV=addon
script:
  - tox -e $TOX_ENV
