frontend-watcher:
  build: .
  dockerfile: Dockerfile-frontend-build
  volumes:
    - .:/app
  environment:
    - NODE_ENV=development
  command:
    ./bin/run-frontend-watch.sh
server:
  build: .
  dockerfile: Dockerfile
  ports:
    - "8000:8000"
  volumes:
    - .:/app
  command:
    ./bin/run-dev.sh
  environment:
    - PYTHONUNBUFFERED=1
    - PYTHONDONTWRITEBYTECODE=1
    - DATABASE_URL=postgres://postgres@db/postgres
    - DEBUG=True
    - INITIAL_ADMIN_USERNAME=admin
    - INITIAL_ADMIN_PASSWORD=admin
    - INITIAL_ADMIN_EMAIL=admin@example.com
    - ALLOWED_HOSTS=ideatown.dev
    - SECRET_KEY=59114b6a-2858-4caf-8878-482a24ee9542
    - FXA_ACCESS_TOKEN_URL=https://oauth-stable.dev.lcip.org/v1/token
    - FXA_AUTHORIZE_URL=https://oauth-stable.dev.lcip.org/v1/authorization
    - FXA_PROFILE_URL=https://stable.dev.lcip.org/profile/v1/profile
    - FXA_CLIENT_ID=2e13dbd92f77f7df
    - FXA_SECRET_KEY=a93644d71fa684da464fd2dba4d687c14cb21e1dd740af83895e70ede82f54cc
    - DATADOG_API_KEY=4f3b967bbf13c7769ac4fa89efda0fae
    - DATADOG_APP_KEY=ddd45a7b3a3cb90ff1baf20ae8cfab04d1937038
