frontend-watcher:
  build: .
  dockerfile: Dockerfile-frontend-build
  ports:
    - "9966:9966"
  volumes:
    - .:/app
  environment:
    - NODE_ENV=development
  command:
    ./bin/run-frontend-watch.sh
server:
  build: .
  dockerfile: Dockerfile
  ports:
    - "8000:8000"
  # HACK: escalate to root user in dev, because we need to be able to write
  # file uploads to /app/media. Production will use Amazon S3
  user: root
  volumes:
    - .:/app
  command:
    ./bin/run-dev.sh
  environment:
    - PYTHONUNBUFFERED=1
    - PYTHONDONTWRITEBYTECODE=1
    - DATABASE_URL=postgres://postgres@db/postgres
    - DEBUG=True
    - INITIAL_ADMIN_USERNAME=admin
    - INITIAL_ADMIN_PASSWORD=admin
    - INITIAL_ADMIN_EMAIL=admin@example.com
    - ALLOWED_HOSTS=testpilot.dev
    - SECRET_KEY=59114b6a-2858-4caf-8878-482a24ee9542
    - FXA_ACCESS_TOKEN_URL=https://oauth-stable.dev.lcip.org/v1/token
    - FXA_AUTHORIZE_URL=https://oauth-stable.dev.lcip.org/v1/authorization
    - FXA_PROFILE_URL=https://stable.dev.lcip.org/profile/v1/profile
    - FXA_CLIENT_ID=4636d485f6f0c761
    - FXA_SECRET_KEY=c19cca573b94fc195377c577d29f460ab638bec9c8e2b42b1296bd6b22319778
    - DATADOG_API_KEY=4f3b967bbf13c7769ac4fa89efda0fae
    - DATADOG_APP_KEY=ddd45a7b3a3cb90ff1baf20ae8cfab04d1937038
    - ACCOUNT_INVITE_ONLY_MODE=False
    - MOZILLIANS_API_KEY=ff33fa1255ce0ad59be17271093ab851c6357936
    - DJANGO_LOG_LEVEL=DEBUG
    - DJANGO_LOG_FORMAT=json
